name: test-CI
on: push

test:
 using: unbunt-latest
  steps: 
    - uses: actions/setup-python@v3
    - run: |
        python -m pip install --upgrade pip
        from ghapi.core import GhApi
        pip install -Uq git+https://github.com/fastai/ghapi.git
        api = GhApi(owner='tensorflow', repo='tensorflow')
        api.delete_branch('new-branch')
 
