name: test-CI
on: push

jobs:  
  test-nbdev-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v3
    - run: |
        python -m pip install --upgrade pip
        pip install -Uq git+https://github.com/fastai/ghapi.git
    - run: |
        from ghapi.core import GhApi
        api = GhApi(owner='tensorflow', repo='tensorflow')
        api.delete_branch('new-branch')
 
