name: test-CI
on: push

jobs:  
  test-nbdev-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v3
    - uses: actions/checkout@v4
    - run: |
        python -m pip install --upgrade pip
        pip install -Uq git+https://github.com/fastai/ghapi.git
    - name: run as script
      shell: bash
      run: python script.py
    - name: test py
      shell: python
      run: |
        from ghapi.core import GhApi
        api = GhApi(owner='tensorflow', repo='tensorflow', token="${{ secrets.GITHUB_TOKEN }}")
        api.delete_branch('new-branch')
      

